"""fix password

Revision ID: 1aa22ae41491
Revises: 4acbf53b2615
Create Date: 2023-12-15 15:34:19.691961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa22ae41491'
down_revision = '4acbf53b2615'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
