"""add foreignkey to pets

Revision ID: 4acbf53b2615
Revises: 0ac393f33098
Create Date: 2023-12-07 22:35:35.964197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acbf53b2615'
down_revision = '0ac393f33098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('password', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_column('pets', 'owner_id')
    # ### end Alembic commands ###
